#!/usr/bin/env bash
set -euo pipefail
usage() { printf 'usage: %s <silent-video> <music-file> <out-file> [target-lufs]\n' "$0" >&2; exit 2; }
[[ $# -ge 3 && $# -le 4 ]] || usage
silent_video=$1; music_file=$2; out_file=$3; target_lufs=${4:--16}
for required_file in "$silent_video" "$music_file"; do [[ -f "$required_file" ]] || { printf 'missing input: %s\n' "$required_file" >&2; exit 1; }; done
find_media_tool() { if command -v "$1" >/dev/null 2>&1; then command -v "$1"; elif [[ -x "$HOME/.local/bin/$1" ]]; then printf '%s\n' "$HOME/.local/bin/$1"; else printf 'required tool not found: %s\n' "$1" >&2; exit 1; fi; }
ffmpeg_bin=$(find_media_tool ffmpeg); ffprobe_bin=$(find_media_tool ffprobe); mkdir -p "$(dirname "$out_file")"; video_duration=$("$ffprobe_bin" -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$silent_video")
[[ "$video_duration" =~ ^[0-9]+([.][0-9]+)?$ ]] || { printf 'could not measure video duration\n' >&2; exit 1; }
pass_one=$("$ffmpeg_bin" -hide_banner -nostats -i "$music_file" -af "loudnorm=I=${target_lufs}:TP=-1.0:LRA=11:print_format=json" -f null - 2>&1 >/dev/null)
json_value() { local key=$1; printf '%s\n' "$pass_one" | awk -v key="$key" '$0 ~ "\\\"" key "\\\"" {value=$0; sub(/.*:[[:space:]]*/, "", value); gsub(/[,"]/, "", value); gsub(/[[:space:]]/, "", value); print value; exit}'; }
input_i=$(json_value input_i); input_tp=$(json_value input_tp); input_lra=$(json_value input_lra); input_thresh=$(json_value input_thresh); target_offset=$(json_value target_offset)
for measurement in "$input_i" "$input_tp" "$input_lra" "$input_thresh" "$target_offset"; do [[ "$measurement" =~ ^-?[0-9]+([.][0-9]+)?$ ]] || { printf 'loudnorm measurement missing or invalid: %s\n' "$measurement" >&2; exit 1; }; done
"$ffmpeg_bin" -y -hide_banner -nostats -i "$silent_video" -stream_loop -1 -i "$music_file" -filter_complex "[1:a]aloop=loop=-1:size=2147483647,atrim=duration=${video_duration},loudnorm=I=${target_lufs}:TP=-1.0:LRA=11:measured_I=${input_i}:measured_TP=${input_tp}:measured_LRA=${input_lra}:measured_thresh=${input_thresh}:offset=${target_offset}:linear=true:print_format=summary[a]" -map 0:v:0 -map '[a]' -c:v copy -c:a aac -ar 48000 -ac 2 -shortest "$out_file"
video_codec=$("$ffprobe_bin" -v error -select_streams v:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 "$out_file"); audio_codec=$("$ffprobe_bin" -v error -select_streams a:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 "$out_file"); sample_rate=$("$ffprobe_bin" -v error -select_streams a:0 -show_entries stream=sample_rate -of default=noprint_wrappers=1:nokey=1 "$out_file"); channels=$("$ffprobe_bin" -v error -select_streams a:0 -show_entries stream=channels -of default=noprint_wrappers=1:nokey=1 "$out_file")
printf 'codecs: video=%s, audio=%s, sample_rate=%s Hz, channels=%s\n' "$video_codec" "$audio_codec" "$sample_rate" "$channels"; [[ -n "$video_codec" && "$audio_codec" == aac && "$sample_rate" == 48000 && "$channels" == 2 ]] || { printf 'output codec verification failed\n' >&2; exit 1; }
loudness_report=$("$ffmpeg_bin" -hide_banner -nostats -i "$out_file" -filter_complex ebur128=peak=true -f null - 2>&1 >/dev/null); measured_lufs=$(printf '%s\n' "$loudness_report" | awk '/Integrated loudness:/ {want_i=1; next} want_i && /^[[:space:]]*I:/ {print $2; want_i=0}'); true_peak=$(printf '%s\n' "$loudness_report" | awk '/True peak:/ {want_peak=1; next} want_peak && /^[[:space:]]*Peak:/ {print $2; want_peak=0}')
[[ "$measured_lufs" =~ ^-?[0-9]+([.][0-9]+)?$ ]] || { printf 'could not measure integrated loudness\n' >&2; exit 1; }; [[ "$true_peak" =~ ^-?[0-9]+([.][0-9]+)?$ ]] || { printf 'could not measure true peak\n' >&2; exit 1; }; printf 'LUFS: %s (target %s)\n' "$measured_lufs" "$target_lufs"; printf 'true peak: %s\n' "$true_peak"
awk -v measured="$measured_lufs" -v target="$target_lufs" -v peak="$true_peak" 'BEGIN {difference=measured-target; if (difference < 0) difference=-difference; exit(difference > 1.5 || peak > -1)}' || { printf 'loudness verification failed\n' >&2; exit 1; }
